---
title: "stat_analysis"
author: "Ryan Wei"
date: "2024-03-19"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source(knitr::purl("./data_manipulation.Rmd", quiet=TRUE))
source(knitr::purl("./EDA.Rmd", quiet=TRUE))
```

```{r table1}
data.baseline <- data.comp %>% filter(day == 0)

library(table1)
data.baseline$gender = ifelse(data.baseline$gender == "M", "Male", "Female")
label(data.baseline$age) = "Age"
label(data.baseline$gender) = "Gender"
label(data.baseline$treatment_group) = "Treatment"
label(data.baseline$mem_comp) = "Baseline Composite Memory Score"
my.render.cont <- function(x) {
    with(stats.default(x), 
        sprintf("%0.2f (%0.1f)", MEAN, SD))
}

tbl1 <- table1( ~ gender + age + mem_comp | treatment_group, data=data.baseline, render.continuous=my.render.cont) %>% t1kable(booktabs = TRUE, format = "latex") %>%  kable_styling(latex_options = c("hold_position", "scale_down"))

writeLines(as.character(tbl1), "tbl1.tex")
```


```{r}
# centering age for better interpretation
data.full$age = data.full$age - mean(data.full$age)
data.comp$age = data.comp$age - mean(data.comp$age)
data.surv$age = data.surv$age - mean(data.surv$age)
```


# Complete case GEE

```{r model-complete-case-gee}
library(gee)
library(geepack)
library(glmtoolbox)
library(gtsummary)
library(tidyverse)
data.comp.lag <-
  data.comp %>% 
  group_by(subject_id) %>% 
  mutate(mem_comp_lag = lag(mem_comp), observed_lag = lag(observed)) %>% 
  ungroup() %>% 
  filter(observed_lag != 0) %>% 
  mutate(drop = ifelse(observed == 0 & observed_lag == 1, 1, 0)) %>% 
  dplyr::select(subject_id, day, day_fct, age, gender, treatment_group, mem_comp_lag, drop) %>% 
  mutate(day_fct = factor(day, levels = c(5,19,90)))

data.comp <- 
  data.comp %>% 
  group_by(subject_id) %>% 
  mutate(total_obs = sum(as.numeric(observed))) %>% 
  ungroup() %>% 
  mutate(type = as.factor(ifelse(total_obs == 4, "Completer", "Drop-out")))


model.complete.1 <- geeglm(mem_comp ~ day_fct + treatment_group + age + gender + treatment_group * day_fct, data = data.comp %>% filter(type=="Completer"), family = gaussian, id = subject_id, corstr = "independence")
model.complete.2 <- geeglm(mem_comp ~ day_fct + treatment_group + age + gender + treatment_group * day_fct, data = data.comp %>% filter(type=="Completer"), family = gaussian, id = subject_id,  corstr = "ar1")
model.complete.3 <- geeglm(mem_comp ~ day_fct + treatment_group + age + gender + treatment_group * day_fct, data = data.comp %>% filter(type=="Completer"), family = gaussian, id = subject_id, corstr = "exchangeable")

model.complete.1.tbl <- tbl_regression(model.complete.1,label = list(
      day_fct ~ "Days",
      treatment_group ~ "Treatment",
      age ~ "Age",
      gender ~ "Gender",
      `day_fct:treatment_group` ~ "Days*Treatment"
    )) %>% 
  modify_header(
  update = list(p.value = "p-value", ci = "95% CI", label = "Characteristics", estimate = "Beta")
  ) 
model.complete.2.tbl <- tbl_regression(model.complete.2,label = list(
      day_fct ~ "Days",
      treatment_group ~ "Treatment",
      age ~ "Age",
      gender ~ "Gender",
      `day_fct:treatment_group` ~ "Days*Treatment"
    )) %>% 
  modify_header(
  update = list(p.value = "p-value", ci = "95% CI", label = "Characteristics", estimate = "Beta")
  ) 
model.complete.3.tbl <- tbl_regression(model.complete.3,label = list(
      day_fct ~ "Days",
      treatment_group ~ "Treatment",
      age ~ "Age",
      gender ~ "Gender",
      `day_fct:treatment_group` ~ "Days*Treatment"
    )) %>% 
  modify_header(
  update = list(p.value = "p-value", ci = "95% CI", label = "Characteristics", estimate = "Beta")
  ) 

model.complete.tbl <-
  tbl_merge(list(model.complete.1.tbl, model.complete.2.tbl, model.complete.3.tbl), tab_spanner = c("Independent","AR-1","Exchangable")) %>% as_kable(booktabs = T, format = "latex",escape = FALSE) %>%  kable_styling(latex_options = c("hold_position")) %>% add_header_above(c(" ", "Independent" = 3, "AR-1" = 3, "Exchangable" = 3))
model.complete.tbl
writeLines(as.character(model.complete.tbl), "complete_case_gee.tex")
```


# Testing MCAR

```{r model-test-mcar}
model.drop <-
  geeglm(drop ~ day_fct + treatment_group + age + gender + mem_comp_lag, data = data.comp.lag, family = binomial, id = subject_id, corstr = "independence")

tbl_regression(model.drop, exponentiate = F)
```
No significant evidence of violating MCAR...

# Linear mixed effect models

```{r model-lmer}
library(lme4)
library(nlme)
library(lattice)
library(knitr)
library(kableExtra)

model.lmer = lmer(
  mem_comp ~ day_fct + treatment_group + age + gender + treatment_group * day_fct + (1 |subject_id), data = data.comp
)

tbl_regression(model.lmer)
```


# IPW GEE

```{r model-ps}
# propensity score models, using logistic regression and coxph model 
model.prob.drop <-
  geeglm(dropped ~ day_fct + treatment_group + age + gender, data = data.surv %>% mutate(day_fct = factor(day_fct,levels = c(5,19,90))), family = binomial, id = subject_id, corstr = "independence")

model.prob.drop.coxph <- coxph(Surv(start, stop, dropped) ~ treatment_group + age + gender, data = data.surv)

model.prob.drop.tbl <- tbl_regression(model.prob.drop, exponentiate = T,label = list(
      day_fct ~ "Days",
      treatment_group ~ "Treatment",
      age ~ "Age",
      gender ~ "Gender"
    )) %>% 
  modify_header(
  update = list(p.value = "p-value", ci = "95% CI", label = "Characteristics", estimate = "OR")
  )  %>% as_kable(booktabs = T, format = "latex",escape = FALSE) %>%  kable_styling(latex_options = c("hold_position"))

writeLines(as.character(model.prob.drop.tbl), "ps_model.tex")

tbl_regression(model.prob.drop.coxph, exponentiate = F)

tbl_merge(
  list(tbl_regression(model.prob.drop, exponentiate = F),tbl_regression(model.prob.drop.coxph, exponentiate = F))
)

predict.prob.drop <- predict(model.prob.drop, newdata = data.surv, type = "response")
predict.prob.drop.coxph <- predict(model.prob.drop.coxph, newdata = data.surv, type = "survival")

data.surv$prob.stay <- 1 - predict.prob.drop
data.surv$prob.stay.coxph <- predict.prob.drop.coxph

data.comp <- left_join(data.comp, data.surv %>% dplyr::select(subject_id,day_fct,treatment_group,prob.stay, prob.stay.coxph))
data.comp <-
  data.comp %>% 
  mutate(
    prob.stay = ifelse(day_fct==0, 1, prob.stay),
    prob.stay.coxph = ifelse(day_fct==0, 1, prob.stay.coxph)
  )
```
```{r model-ipw-gee}
model.ipw.1 <- geeglm(mem_comp ~ day_fct + treatment_group + age + gender + treatment_group * day_fct, data = data.comp, family = gaussian, id = subject_id, corstr = "independence", weights = 1/prob.stay)
model.ipw.2 <- geeglm(mem_comp ~ day_fct + treatment_group + age + gender + treatment_group * day_fct, data = data.comp, family = gaussian, id = subject_id,  corstr = "ar1", weights = 1/prob.stay)
model.ipw.3 <- geeglm(mem_comp ~ day_fct + treatment_group + age + gender + treatment_group * day_fct, data = data.comp, family = gaussian, id = subject_id, corstr = "exchangeable", weights = 1/prob.stay)


tbl_merge(
  list(tbl_regression(model.ipw.1), tbl_regression(model.ipw.2), tbl_regression(model.ipw.3))
)
```
```{r model-ipw-gee-coxph}
model.ipw.coxph.1 <- geeglm(mem_comp ~ day_fct + treatment_group + age + gender + treatment_group * day_fct, data = data.comp, family = gaussian, id = subject_id, corstr = "independence", weights = 1/prob.stay.coxph)
model.ipw.coxph.2 <- geeglm(mem_comp ~ day_fct + treatment_group + age + gender + treatment_group * day_fct, data = data.comp, family = gaussian, id = subject_id,  corstr = "ar1", weights = 1/prob.stay.coxph)
model.ipw.coxph.3 <- geeglm(mem_comp ~ day_fct + treatment_group + age + gender + treatment_group * day_fct, data = data.comp, family = gaussian, id = subject_id, corstr = "exchangeable", weights = 1/prob.stay.coxph)


tbl_merge(
  list(tbl_regression(model.ipw.coxph.1), tbl_regression(model.ipw.coxph.2), tbl_regression(model.ipw.coxph.3))
)
```



# Sensitivity analysis

```{r}
data.comp %>% 
    group_by(day_fct) %>% 
    summarise(observed = round(sum(!is.na(mem_comp))/158,digits=2), missing = round(sum(is.na(mem_comp))/30, digits = 2))
temp <- matrix(c(47, 45, 35, 31, 0, 2, 12, 16),nrow=4,ncol=2)
chisq.test(temp,correct=FALSE)



data.comp %>% 
    group_by(gender) %>% 
    summarise(observed = round(sum(!is.na(mem_comp))/158,digits=2), missing = round(sum(is.na(mem_comp))/30, digits = 2))
temp <- matrix(c(87, 71, 13, 17),nrow=2,ncol=2)
chisq.test(temp,correct=FALSE)
 


data.comp %>% 
    group_by(treatment_group) %>% 
    summarise(observed = round(sum(!is.na(mem_comp))/158,digits=2), missing = round(sum(is.na(mem_comp))/30, digits = 2))
temp <- matrix(c(58, 46, 54, 10, 10, 10),nrow=2,ncol=2)
chisq.test(temp,correct=FALSE)
```

